palette:
  top: '#d0d0d0'
  bottom: '#c2c4c5'
  bg: '#ffffff'
  sidebar: '#ffffff'
  sidebarborders: '#cccccc'
  footer: '#016b83'
  button: '#019dbf'
  buttonhover: '#016c83'
  titleslogan: '#000000'
  text: '#4a4a4a'
  link: '#019dbf'
logo: 'public://color/omd-72b92485/logo.svg'
stylesheets:
  - 'public://color/omd-72b92485/colors.css'
files:
  - 'public://color/omd-72b92485/logo.svg'
  - 'public://color/omd-72b92485/colors.css'
