module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  bootstrap_paragraphs: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  config: 0
  contextual: 0
  ctools: 0
  datetime: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  facets: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  schema_metatag: 0
  schema_organization: 0
  search_api: 0
  search_api_db: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  views_ui: 0
  viewsreference: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  minimalplus: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: de
